openapi: 3.0.0

info:
  title: "GameAP Web API"
  version: "1.0.0"

servers:
  - url: "{gameap-host}/api"
    variables:
      gameap-host:
        default: https://demo.gameap.ru
        description: GameAP Host

security:
  - cookieAuth: []

paths:
  /dedicated_servers/{dedicated_server}/ip_list:
    $ref: './web-api/paths/dedicated_servers_id_ip_list.yaml'

  /dedicated_servers/{dedicated_server}/busy_ports:
    $ref: './web-api/paths/dedicated_servers_id_busy_ports.yaml'

  /game_mods/get_list_for_game/{game}:
    $ref: './web-api/paths/game_mods_get_list_for_game.yaml'

  /servers:
    $ref: './web-api/paths/servers.yaml'

  /servers/{server}:
    $ref: './web-api/paths/servers_id.yaml'

  /servers/{server}/start:
    $ref: './web-api/paths/servers_id_start.yaml'

  /servers/{server}/stop:
    $ref: './web-api/paths/servers_id_stop.yaml'

  /servers/{server}/restart:
    $ref: './web-api/paths/servers_id_restart.yaml'

  /servers/{server}/update:
    $ref: './web-api/paths/servers_id_update.yaml'

  /servers/{server}/reinstall:
    $ref: './web-api/paths/servers_id_reinstall.yaml'

  /servers/{server}/status:
    $ref: './web-api/paths/servers_id_status.yaml'

  /servers/{server}/query:
    $ref: './web-api/paths/servers_id_query.yaml'

  /servers/{server}/console:
    $ref: './web-api/paths/servers_id_console.yaml'

  /servers/search:
    $ref: './web-api/paths/servers_search.yaml'

  /gdaemon_tasks/{gdaemon_task}:
    $ref: './web-api/paths/gdaemon_tasks_id.yaml'

  /gdaemon_tasks/{gdaemon_task}/output:
    $ref: './web-api/paths/gdaemon_tasks_id_output.yaml'

components:
  securitySchemes:
    cookieAuth:
      description: Auth Cookies
      type: apiKey
      in: cookie
      name: laravel_session
    tokenAuth:
        description: Auth Token
        type: apiKey
        in: header
        name: Authorization

  requestBodies:
    CommonRequest:
      content:
        application/json:
          schema:
            type: object

  responses:
    CommonSuccessResponse:
      $ref: './web-api/responses/common-success.yaml'
    CommonErrorResponse:
      $ref: './web-api/responses/common-error.yaml'
